Test-PTSLSSS: Test-PTSLSSS.c Lib-Mesg.c Lib-Mesg.h Lib-PTSLSSS.c Lib-PTSLSSS.h Lib-Timing.c Lib-Timing.h Lib-Utils.c Lib-Utils.h
	gcc Test-PTSLSSS.c Lib-Mesg.c Lib-PTSLSSS.c Lib-Timing.c Lib-Utils.c -lm -lgmp -lnettle -lpbc -o Test-PTSLSSS
